export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_ALL_TODO_TASKS_SUCCESS = 'LOAD_ALL_TODO_TASKS_SUCCESS';
export const CREATE_NEW_TODO_TASK_SUCCESS = 'CREATE_NEW_TODO_TASK_SUCCESS';
export const DELETE_TODO_TASK_SUCCESS = 'DELETE_TODO_TASK_SUCCESS';
export const COMPLETE_TODO_TASK_SUCCESS = 'COMPLETE_TODO_TASK_SUCCESS';
export const UPDATE_TODO_TASK_SUCCESS = 'UPDATE_TODO_TASK_SUCCESS';